# Generated by Django 5.2.11 on 2026-02-26 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("doctors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_number", models.PositiveIntegerField()),
                ("token_display", models.CharField(max_length=10)),
                ("priority", models.PositiveIntegerField(default=1)),
                ("notes", models.TextField(blank=True, null=True)),
                ("arrival_time", models.DateTimeField(blank=True, null=True)),
                ("called_time", models.DateTimeField(blank=True, null=True)),
                (
                    "consultation_start_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("consultation_end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("called", "Called"),
                            ("in_consultation", "In Consultation"),
                            ("completed", "Completed"),
                            ("missed", "Missed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("is_walk_in", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_tokens",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_tokens",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Queue Token",
                "verbose_name_plural": "Queue Tokens",
                "ordering": ["-priority", "token_number", "created_at"],
            },
        ),
    ]
