# Generated by Django 5.2.11 on 2026-02-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="prescription",
            name="emailed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
