# Generated by Django 5.2.11 on 2026-02-26 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_prescription_email_sent_prescription_emailed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrescriptionMedicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=200)),
                ("dose", models.CharField(blank=True, max_length=100, null=True)),
                ("times_per_day", models.PositiveIntegerField(default=1)),
                ("duration_days", models.PositiveIntegerField(default=1)),
                ("quantity_tablets", models.PositiveIntegerField(default=1)),
                (
                    "timing",
                    models.CharField(
                        choices=[
                            ("before_food", "Before Food"),
                            ("after_food", "After Food"),
                            ("with_food", "With Food"),
                            ("bedtime", "Bedtime"),
                            ("custom", "Custom"),
                        ],
                        default="after_food",
                        max_length=20,
                    ),
                ),
                (
                    "instruction",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicine_items",
                        to="billing.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription Medicine",
                "verbose_name_plural": "Prescription Medicines",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
