# Generated by Django 5.2.11 on 2026-02-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_prescriptionmedicine"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cash_enabled", models.BooleanField(default=True)),
                ("online_enabled", models.BooleanField(default=False)),
                ("upi_id", models.CharField(blank=True, max_length=120, null=True)),
                ("upi_qr_image_url", models.URLField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Clinic Settings",
                "verbose_name_plural": "Clinic Settings",
            },
        ),
    ]
