# Generated by Django 5.2.11 on 2026-02-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_clinicsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="email_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bill",
            name="emailed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
