# Generated by Django 5.2.11 on 2026-02-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_notificationdelivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicsettings",
            name="sms_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clinicsettings",
            name="whatsapp_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
